"""initial schema

Revision ID: f1a21bc35951
Revises: 
Create Date: 2026-09-06 23:39:11.153468
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.database  # noqa: F401 - portable JSONColumn / UTCDateTime types

revision: str = 'f1a21bc35951'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('slug', sa.String(length=240), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('cover_image', sa.String(length=512), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('tags', app.core.database.JSONColumn(), nullable=False),
    sa.Column('reading_minutes', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('published_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('seo_title', sa.String(length=240), nullable=True),
    sa.Column('seo_description', sa.String(length=400), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_blog_posts'))
    )
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_table('templates',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=48), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ats_rating', sa.Integer(), nullable=False),
    sa.Column('preview_image', sa.String(length=512), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('layout', sa.String(length=32), nullable=False),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('experience_levels', app.core.database.JSONColumn(), nullable=False),
    sa.Column('industries', app.core.database.JSONColumn(), nullable=False),
    sa.Column('badges', app.core.database.JSONColumn(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('template_config', app.core.database.JSONColumn(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates'))
    )
    op.create_index(op.f('ix_templates_category'), 'templates', ['category'], unique=False)
    op.create_index(op.f('ix_templates_slug'), 'templates', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('onboarding', app.core.database.JSONColumn(), nullable=False),
    sa.Column('preferences', app.core.database.JSONColumn(), nullable=False),
    sa.Column('last_login_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('error_events',
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('meta', app.core.database.JSONColumn(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_error_events_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_error_events'))
    )
    op.create_table('job_descriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extracted_keywords', app.core.database.JSONColumn(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_job_descriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_descriptions'))
    )
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    op.create_table('oauth_accounts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_accounts_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_accounts'))
    )
    op.create_index('uq_oauth_provider_account', 'oauth_accounts', ['provider', 'provider_account_id'], unique=True)
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('replaced_by', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index('ix_refresh_tokens_user_id_expires_at', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_table('resumes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('data', app.core.database.JSONColumn(), nullable=False),
    sa.Column('settings', app.core.database.JSONColumn(), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tailored_for', sa.String(length=200), nullable=True),
    sa.Column('source_resume_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_resume_id'], ['resumes.id'], name=op.f('fk_resumes_source_resume_id_resumes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_resumes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resumes'))
    )
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index('ix_resumes_user_id_updated_at', 'resumes', ['user_id', 'updated_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('amount_usd', sa.String(length=16), nullable=True),
    sa.Column('start_date', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('end_date', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('canceled_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('meta', app.core.database.JSONColumn(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    op.create_index(op.f('ix_subscriptions_provider_subscription_id'), 'subscriptions', ['provider_subscription_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('usage_events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('meta', app.core.database.JSONColumn(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_usage_events_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usage_events'))
    )
    op.create_index(op.f('ix_usage_events_action'), 'usage_events', ['action'], unique=False)
    op.create_index('ix_usage_events_user_action_created', 'usage_events', ['user_id', 'action', 'created_at'], unique=False)
    op.create_index(op.f('ix_usage_events_user_id'), 'usage_events', ['user_id'], unique=False)
    op.create_table('ats_reports',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('job_description_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('formatting_score', sa.Integer(), nullable=False),
    sa.Column('keyword_score', sa.Integer(), nullable=False),
    sa.Column('content_score', sa.Integer(), nullable=False),
    sa.Column('experience_score', sa.Integer(), nullable=False),
    sa.Column('skills_score', sa.Integer(), nullable=False),
    sa.Column('education_score', sa.Integer(), nullable=False),
    sa.Column('completeness_score', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('issues', app.core.database.JSONColumn(), nullable=False),
    sa.Column('recommendations', app.core.database.JSONColumn(), nullable=False),
    sa.Column('strengths', app.core.database.JSONColumn(), nullable=False),
    sa.Column('matched_keywords', app.core.database.JSONColumn(), nullable=False),
    sa.Column('missing_keywords', app.core.database.JSONColumn(), nullable=False),
    sa.Column('sections', app.core.database.JSONColumn(), nullable=False),
    sa.Column('summary', app.core.database.JSONColumn(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name=op.f('fk_ats_reports_job_description_id_job_descriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_ats_reports_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ats_reports_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ats_reports'))
    )
    op.create_index(op.f('ix_ats_reports_resume_id'), 'ats_reports', ['resume_id'], unique=False)
    op.create_index('ix_ats_reports_user_created', 'ats_reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ats_reports_user_id'), 'ats_reports', ['user_id'], unique=False)
    op.create_table('resume_versions',
    sa.Column('resume_id', sa.Uuid(), nullable=False),
    sa.Column('version_name', sa.String(length=160), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('data', app.core.database.JSONColumn(), nullable=False),
    sa.Column('settings', app.core.database.JSONColumn(), nullable=False),
    sa.Column('template_id', sa.String(length=64), nullable=False),
    sa.Column('ats_score', sa.Integer(), nullable=True),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_resume_versions_resume_id_resumes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_versions'))
    )
    op.create_index('ix_resume_versions_resume_created', 'resume_versions', ['resume_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_resume_versions_resume_id'), 'resume_versions', ['resume_id'], unique=False)
    op.create_table('applications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_title', sa.String(length=200), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resume_id', sa.Uuid(), nullable=True),
    sa.Column('job_description_id', sa.Uuid(), nullable=True),
    sa.Column('ats_report_id', sa.Uuid(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ats_report_id'], ['ats_reports.id'], name=op.f('fk_applications_ats_report_id_ats_reports'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], name=op.f('fk_applications_job_description_id_job_descriptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], name=op.f('fk_applications_resume_id_resumes'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index(op.f('ix_applications_user_id'), 'applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_user_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_resume_versions_resume_id'), table_name='resume_versions')
    op.drop_index('ix_resume_versions_resume_created', table_name='resume_versions')
    op.drop_table('resume_versions')
    op.drop_index(op.f('ix_ats_reports_user_id'), table_name='ats_reports')
    op.drop_index('ix_ats_reports_user_created', table_name='ats_reports')
    op.drop_index(op.f('ix_ats_reports_resume_id'), table_name='ats_reports')
    op.drop_table('ats_reports')
    op.drop_index(op.f('ix_usage_events_user_id'), table_name='usage_events')
    op.drop_index('ix_usage_events_user_action_created', table_name='usage_events')
    op.drop_index(op.f('ix_usage_events_action'), table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_provider_subscription_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_resumes_user_id_updated_at', table_name='resumes')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('ix_refresh_tokens_user_id_expires_at', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('uq_oauth_provider_account', table_name='oauth_accounts')
    op.drop_table('oauth_accounts')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    op.drop_table('error_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_templates_slug'), table_name='templates')
    op.drop_index(op.f('ix_templates_category'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
